<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<section class="completed">
	<h2>Conclusie</h2>
	<dl>
	<?php foreach ($domain->goals as $goal): ?>
		<?php if ($goal->hasAnswers() && (($answer = $goal->answer($state)) || $state->facts[$goal->name] != STATE_UNDEFINED)): ?>
			<?php if ($answer->aangifteplicht): ?>
				<h4 class="aangifte">Let op! Dit is een aangifteplichtige ziekte, meld deze bij de nVWA.</h4>
			<?php endif ?>
			<dt><?=$state->substitute_variables($goal->description, ['Template', 'html'])?>Diagnose</dt>
			<dd><?php
				echo $answer
					? $state->substitute_variables($answer->diagnose, ['Template', 'html'])
					: '<pre>' . $state->facts[$goal->name] . '</pre>';
				?></dd>
			<dt><?=$state->substitute_variables($goal->description, ['Template', 'html'])?>Behandeling</dt>
			<dd><?php
				echo $answer
					? $state->substitute_variables($answer->behandeling, ['Template', 'html'])
					: '<pre>' . $state->facts[$goal->name] . '</pre>';
				?></dd>
			<?php if ($answer->preventief != ''): ?>
			<dt><?=$state->substitute_variables($goal->description, ['Template', 'html'])?>Preventief</dt>
			<dd><?php
				echo $answer
					? $state->substitute_variables($answer->preventief, ['Template', 'html'])
					: '<pre>' . $state->facts[$goal->name] . '</pre>';
				?></dd>
			<?php endif?>
			<?php if ($answer->opmerkingen != ''): ?>
			<dt><?=$state->substitute_variables($goal->description, ['Template', 'html'])?>Opmerkingen</dt>
			<dd><?php
				echo $answer
					? $state->substitute_variables($answer->opmerkingen, ['Template', 'html'])
					: '<pre>' . $state->facts[$goal->name] . '</pre>';
				?></dd>
			<?php endif ?>
		<?php endif ?>
	<?php endforeach ?>
	</dl>
</section>
<?php $this->end() ?>