<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<section class="question">
	<h3><?=$state->substitute_variables($question->description, ['Template', 'html'])?></h3>

	<ol class="optionsMultiple">
		<?php foreach ($question->options as $option): ?>
		<li>
			<label>
				<input type="hidden" name="answers[]" value="<?=_encode($option->ifNotConsequences)?>">
				<input type="checkbox" name="answers[]" value="<?=_encode($option->consequences)?>">
				<?=$state->substitute_variables($option->description, ['Template', 'html'])?>
			</label>
		</li>
		<?php endforeach ?>
	</ol>

	<button class= "button" type="submit">Ga door...</button>

	<div class="imagesRow">
		<?php foreach ($question->images as $image): ?>
		<div class="imagesCol">
			 <figure>
  				<img src="<?=$state->substitute_variables($image->file, ['Template', 'html'])?>" alt="Sheep" style="width:100%">
  				<figcaption><?=$state->substitute_variables($image->caption, ['Template', 'html'])?></figcaption>
			</figure> 
		</div>
		<?php endforeach ?>
	</div>
</section>
<?php $this->end() ?>