<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<section class="question">
	<p><?=$state->substitute_variables($question->description, ['Template', 'html'])?></p>

	<ol class="optionsMultiple">
		<?php foreach ($question->options as $option): ?>
		<li>
			<label>
				<input type="hidden" name="answers[]" value="<?=_encode($option->ifNotConsequences)?>">
				<input type="checkbox" name="answers[]" value="<?=_encode($option->consequences)?>">
				<?=$state->substitute_variables($option->description, ['Template', 'html'])?>
			</label>
		</li>
		<?php endforeach ?>
	</ol>

	<button type="submit">Ga door...</button>
</section>
<?php $this->end() ?>