<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<section class="question">
	<h3><?=$state->substitute_variables($question->description, ['Template', 'html'])?></h3>

	<ol class="options">
		<?php foreach ($question->options as $option): ?>
		<li>
			<label>
				<input type="radio" name="answer" value="<?=_encode($option->consequences)?>">
				<?=$state->substitute_variables($option->description, ['Template', 'html'])?>
			</label>
		</li>
		<?php endforeach ?>
		<?php if($skippable): ?>
		<li class="skip-option">
			<label>
				<input type="radio" name="answer" value="<?=_encode(array())?>">
				I don't know
			</label>
		</li>
		<?php endif ?>
	</ol>

	<div class="imagesRow">
		<?php foreach ($question->images as $image): ?>
		<div class="imagesCol">
			 <figure>
  				<img src="<?=$state->substitute_variables($image->file, ['Template', 'html'])?>" alt="Sheep" style="width:100%">
  				<figcaption><?=$state->substitute_variables($image->caption, ['Template', 'html'])?></figcaption>
			</figure> 
		</div>
		<?php endforeach ?>
	</div>

</section>
<?php $this->end() ?>