<!DOCTYPE html>
<html>
	<head class="main">
		<title>Wat de herder niet kent...</title>
		<link rel="stylesheet" href="webfrontend.css">
	</head>
	<body class="main">
		<header>
			<h2>Wat de herder niet kent...</h2>
		</header>
		<form method="post">
			<div>
				<h2 class="lookup">...dat zoeken we op!</h2>
				<button type="submit" name="action" value="run" class="button">Begin</button>
			</div>
		</form>
		<div>
			<h3>Beste herder,</h3>
			<p>Wat vervelend dat er iets mis is met je schapen! Om er snel achter te komen wat er aan de hand kan zijn, kun je dit systeem gebruiken. </p>
			<p>Het systeem maakt een diagnose op basis van jouw antwoorden. Verder toont het systeem de mogelijke veroorzakers van het probleem, maatregelen ter preventie en extra informatie. Wanneer er sprake lijkt te zijn van een aangifteplichtige ziekte, zal dit duidelijk worden aangegeven met rode letters. </p>
			<p>Dit systeem is slechts gemaakt ter indicatie en kan geen 100% zekerheid bieden. Wij raden dan ook aan om bij twijfel contact op te nemen met de dierenarts.</p>
		</div>
		<script>
			Array.prototype.forEach.call(
				document.querySelectorAll("a[href^='#']"),
				function(el) {
					console.log(el);
					el.addEventListener('click', function() {
						var hash = el.href.substring(el.href.indexOf('#') + 1);
						var ref = document.getElementById(hash);
						
						Array.prototype.forEach.call(
							document.querySelectorAll('.highlight'),
							function(node) {
								node.classList.remove('highlight')
							});
						
						if (ref)
							ref.classList.add('highlight');
					});
				});
		</script>
	</body>
</html>