<!DOCTYPE html>
<html>
	<head class="main">
		<title>Wat de herder niet kent...</title>
		<link rel="stylesheet" href="webfrontend.css">
	</head>
	<body class="main">
		<header>
			<h2>Wat de herder niet kent...</h2>
		</header>
		<form method="post">
			<div>
				<h2 class="lookup">...dat zoeken we op!</h2>
				<button type="submit" name="action" value="run" class="button">Begin</button>
			</div>
		</form>
		<div>
			<p>Hier komt meer info</p>
		</div>
		<script>
			Array.prototype.forEach.call(
				document.querySelectorAll("a[href^='#']"),
				function(el) {
					console.log(el);
					el.addEventListener('click', function() {
						var hash = el.href.substring(el.href.indexOf('#') + 1);
						var ref = document.getElementById(hash);
						
						Array.prototype.forEach.call(
							document.querySelectorAll('.highlight'),
							function(node) {
								node.classList.remove('highlight')
							});
						
						if (ref)
							ref.classList.add('highlight');
					});
				});
		</script>
	</body>
</html>